# ----------------------------
# Makefile Options
# ----------------------------

NAME = REVERSI
ICON = icon.png
DESCRIPTION = "Reversi game for 84"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
